-- AlterTable
ALTER TABLE "users" ADD COLUMN     "mageEXP" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mageLevel" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "overallEXP" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "overallLevel" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "rogueEXP" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rogueLevel" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "warriorEXP" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "warriorLevel" INTEGER NOT NULL DEFAULT 1;

-- CreateTable
CREATE TABLE "Habit" (
    "id" TEXT NOT NULL,
    "habit" TEXT NOT NULL,
    "habitType" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Habit_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Habit" ADD CONSTRAINT "Habit_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
